### ISSUE TITLE
As a user I want to compare multiple proteomics datasets using the animated pathway visualizations

### ISSUE THREAD

**Issue by phantomas1234** [DD-DeCaF/metabolica-ui-map#43]

**Comment by sgalkina** [comment]
- [ ] upload Uniprot to gene name to ID mapper
- [ ] having the backend (iloop-to-model) return gene names for proteomics
- [ ] make frontend ui element to switch between flux and proteomics
